.github/release-drafter.yml:

name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 Features
    labels:
      - feature
  - title: 🛠 Maintenance
    labels:
      - chore
  - title: 🛠️ Bug Fixes
    labels:
      - bug
change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
template: |
  ## Changes

  ### 🚀 Features
  $CHANGES

  ### 🛠️ Maintenance
  $CHANGES

  ### 🛠️ Bug Fixes
  $CHANGES
