name: Main Workflow

on:
  workflow_dispatch:

jobs:
  setup-tag:
    uses: nookyo/workflow-hub/.github/workflows/docker-tag-template.yml@main

  debug-docker-tag:
    runs-on: ubuntu-latest
    needs: setup-tag
    steps:
      - name: docker tags
        run: echo "docker_tag = ${{ needs.setup-tag.outputs.tag }}"

  build-app:
    needs: setup-tag
    uses: nookyo/workflow-hub/.github/workflows/build-app.yml@main
    with:
      # artifact_name: qip-catalog-library
      # artifact_path: target/qip-catalog-library-*-exec.jar 
      maven_command: "--batch-mode deploy"
    secrets:
      maven_username: ${{ secrets.OSSRH_USERNAME }}
      maven_password: ${{ secrets.OSSRH_TOKEN }}
      maven_gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      maven_gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}