name: Publish Release

on:
  release:
    types:
      - released
  repository_dispatch:
    types:
      - maven-publication-trigger

jobs:
  get_release_version:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version
        run: |
          echo ${{ github.event.client_payload.release_version }}
