name: Release Workflow

on:
   workflow_dispatch:
    inputs:
        revision:
          required: false
          type: string
        release_info:
          required: false
          type: string  
jobs:
  update:
    uses: nookyo/workflow-hub/.github/workflows/update-pom-release.yml@main
    with:
      file: pom.xml
      revision: ${{ github.event.inputs.revision }}

  release:
    uses:  nookyo/workflow-hub/.github/workflows/create-github-release.yml@main
    needs: update
    with:
      revision: ${{ github.event.inputs.revision }}
      release_info: ${{ github.event.inputs.release_info }}
      draft: false
      prerelease: false
