name: Release v2

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '2025.1-1.0.0'
        type: string
        description: 'Custom release version'
      publish:
        required: true
        type: boolean
        default: false
        description: 'Enable publish release?'

jobs:
  pom:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/update-pom-release.yml@main
    with:
       file: pom.xml
       revision: ${{ github.event.inputs.version }}
  release:
    needs: [pom]
    uses:  Netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@feature/actions-usage
    with:
      version: ${{ github.event.inputs.version }}
      publish: ${{ github.event.inputs.publish }}
