name: Release Workflow

on:
   workflow_dispatch:
    inputs:
        revision:
          required: false
          type: string
        release_info:
          required: false
          type: string
        server_id:
          required: false
          type: string
          default: "central"
        java_version:
          required: false
          type: string
          default: "21"  
jobs:
  pom_update:
    uses: nookyo/workflow-hub/.github/workflows/update-pom-release.yml@main
    with:
      file: pom.xml
      revision: ${{ github.event.inputs.revision }}

  git_release:
    uses:  nookyo/workflow-hub/.github/workflows/create-github-release.yml@main
    needs: pom_update
    with:
      revision: ${{ github.event.inputs.revision }}
      release_info: ${{ github.event.inputs.release_info }}
      draft: false
      prerelease: false

  maven:
    uses: nookyo/workflow-hub/.github/workflows/maven-publish.yml@main
    needs: git_release
    with:
      maven_command: "--batch-mode deploy"
      java_version: "21"
    #   server_id: ${{ github.event.inputs.server_id }}
    secrets:
      maven_username: ${{ secrets.OSSRH_USERNAME }}
      maven_password: ${{ secrets.OSSRH_TOKEN }}
      maven_gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      maven_gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}